pkg/datasource.go
Make back-end plugin exit with 1 on error.
=> Backend: Exit with 1 on error

scripts/restart-plugin.sh
Fix killing of plugin process in scripts/restart-plugin.sh.
=> restart-plugin.sh: Fix killing

.golangci.toml, Magefile.go, pkg/datasource.go, pkg/googlesheets/columndefinition/columndefinition.go, pkg/googlesheets/googlesheets.go, pkg/googlesheets/types.go, yarn.lock
Enable linting of style rules, such as documentation comments.
=> Chore: Enable style linting

pkg/datasource.go, pkg/googlesheets/googleclient/googleclient.go, pkg/googlesheets/googlesheets.go, pkg/googlesheets/googlesheets_test.go
Clean up various aspects of back-end code.
=> Chore: Clean up code

pkg/datasource.go, yarn.lock
Enable structured logging in the back-end, as otherwise Grafana won't pick the logs up.
=> Back-end: Fix logging

pkg/googlesheets/columndefinition/columndefinition.go, pkg/googlesheets/columndefinition/columndefinition_test.go, pkg/googlesheets/googlesheets_test.go, yarn.lock
Clean up back-end tests a bit for readability.
=> Back-end: Clean up tests

package.json, pkg/googlesheets/googlesheets.go, pkg/googlesheets/googlesheets_test.go, pkg/googlesheets/testdata/single-cell.json, yarn.lock
Fixes #28
If you select a single row/cell, you should get the values, not the header
=> Support results with a single row

.circleci/config.yml, .gitignore, Magefile.go, go.mod, go.sum, package.json, scripts/debug-backend.sh, src/plugin.json, yarn.lock
=> cross compile

go.mod, go.sum, pkg/datasource.go, pkg/main.go, yarn.lock
this updates so resources will work with master
=> Update SDK to 0.19, and use mux

pkg/googlesheets/googleclient/googleclient.go
the drive API does not work with a key
=> don't check drive unless jwt

go.mod, go.sum, pkg/plugin.go, src/components/ConfigEditor.tsx, yarn.lock
=> Update to v26 use pluginConfig.DataSourceConfig.JSONData rather

Magefile.go, go.mod, go.sum, src/plugin.json, yarn.lock
match some of the script behavior in mage
=> Add linux debug feedback

go.mod, go.sum, pkg/googlesheets/googlesheets.go, pkg/plugin.go, src/DataSource.ts
=> Healthcheck: implement healthcheck endpoint

Magefile.go, yarn.lock
Fix the default target in Magefile.go to be BuildAll.
=> Magefile: Fix default target

.circleci/config.yml, package.json, yarn.lock
Started with adx, now testing with google sheets as it has e2e tests configured.
=> chore: Refactor ci-build process

README.md, package.json
* Document the build routine
* Augment build script in package.json to also build back-end
=> Chore: Document build routine

.circleci/config.yml, .gitignore, cypress/integration/something.ts, package.json, yarn.lock
=> E2E updates

.circleci/config.yml, package.json, yarn.lock
since the current round of e2e work is not targeting running based on the built artifacts, we should not run that in the process...
This tries a much simpler build process
=> CI: simplify ci process

cypress/integration/something.ts
=> E2E improvement

go.mod, go.sum, pkg/googlesheets/googlesheets.go, yarn.lock
Upgrade to latest plugin SDK version. Also fix yarn.lock, so it builds.
=> Chore: Upgrade SDK

cypress/integration/something.ts, cypress/tsconfig.json, yarn.lock
=> Minor E2E updates

.eslintrc.json
This way vscode can pick up eslint rules and can provide feedback on the code.
=> Add eslintrc to root

.github/workflows/lint.yml
this will run `yarn run lint` (which also does `prettier`) when new code is pushed.
=> added lint workflow

pkg/googlesheets/googlesheets.go, pkg/googlesheets/googlesheets_bench_test.go, pkg/googlesheets/testdata/invalid-date-time.json
This PR aims to improve the efficiency of our response processing for data frames. Key changes include:
1. Optimized memory allocations:
- Fixed map/slice allocations where possible to enhance performance.
2. Log cleanup:
- Removed redundant and spammy logs that were not actionable and change some `warning` errors to `debug`, as they are describing normal situation.
3. Better warnings handling
- Display only one warning per column for data conversion issues, rather than one warning per row. This addresses the issue where users with 1,000 rows would receive 1,000 warnings if the system fails to parse a date. Previously:
- Warnings were added to a slice without pre-allocated memory since the number of warnings was unknown.
- All these warnings were added to `DataFrame.Meta`.
- We logged the …
=> Improve efficiency when processing response

README.md
added integration of video and play dashboard so that the video link and also the play demo dashboard is visible inside the Plugin catalog once the user views this plugin.
=> added integration of video and play dashboard

src/README.md
Fixed the README.md to the correct information
=> Fixed the README.md to the correct information
